#!/usr/bin/python3
import math
import sys
import random

def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a

def pollards_rho(number):
    if number % 2 == 0:
        return 2, number // 2

    x = random.randint(1, number - 1)
    y = x
    c = random.randint(1, number - 1)
    d = 1

    def f(x):
        return (x**2 + c) % number

    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), number)

    if d == number:
        return pollards_rho(number)

    return d, number // d

def factorize_number(file_path):
    with open(file_path, 'r') as file:
        number = int(file.read().strip())
        p, q = pollards_rho(number)
        print(f"{number}={p}*{q}")

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: factorize <file>")
        sys.exit(1)
        file_path = sys.argv[1]
        factorize_number(file_path)
